version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-23.11"

conda:
  environment: requirements/dev.yml

sphinx:
  configuration: docs/src/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
