# reference:
#   - https://github.com/actions/cache
#   - https://github.com/actions/checkout

name: ci-tests

on:
  pull_request:

  push:
    branches:
      - "main"
      - "v*x"
      - "!auto-update-lockfiles"
      - "!pre-commit-ci-update-config"
      - "!dependabot/*"
    tags:
      - "v*"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: "${{ matrix.session }} (py${{ matrix.python-version }} ${{ matrix.os }})"

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #: If you change the IRIS_SOURCE here you will also need to change it in
      #: the noxfile and the benchmark and wheel workflows.
      IRIS_SOURCE: "github:main"
      IRIS_TEST_DATA_LOC_PATH: tests
      IRIS_TEST_DATA_PATH: tests/iris-test-data
      IRIS_TEST_DATA_VERSION: "2.19"
      ENV_CACHE_BUILD: "0"
      TEST_DATA_CACHE_BUILD: "0"

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11", "3.12", "3.13"]
        include:
          - python-version: "3.11"
            coverage: true

    steps:
      - name: "checkout"
        uses: actions/checkout@v5

      - name: Install Nox
        run: |
          pip install nox!=2025.05.01

      - name: Cache environment directories
        id: cache-env-dir
        uses: actions/cache@v4
        with:
          path: |
            .nox
            $CONDA/pkgs
          key: ${{ runner.os }}-${{ hashFiles('requirements/locks/') }}-${{ env.ENV_CACHE_BUILD }}-${{ env.IRIS_SOURCE }}-${{ matrix.python-version }}

      - name: Cache test data directory
        id: cache-test-data
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.IRIS_TEST_DATA_PATH }}
          key:
            test-data-${{ env.IRIS_TEST_DATA_VERSION }}-${{ env.TEST_DATA_CACHE_BUILD }}

      - name: Fetch the test data
        if: steps.cache-test-data.outputs.cache-hit != 'true'
        run: |
          wget --quiet https://github.com/SciTools/iris-test-data/archive/v${IRIS_TEST_DATA_VERSION}.zip -O iris-test-data.zip
          unzip -q iris-test-data.zip
          mkdir --parents ${{ github.workspace }}/${IRIS_TEST_DATA_LOC_PATH}
          mv iris-test-data-${IRIS_TEST_DATA_VERSION} ${IRIS_TEST_DATA_PATH}

      - name: Set test data var
        run: |
          echo "OVERRIDE_TEST_DATA_REPOSITORY=${{ github.workspace }}/${IRIS_TEST_DATA_PATH}/test_data" >> $GITHUB_ENV

      - name: "tests (py${{ matrix.python-version }})"
        env:
          PY_VER: ${{ matrix.python-version }}
          COVERAGE: ${{ matrix.coverage }}
        run: |
          nox --session tests -- --verbose

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        if: ${{ matrix.coverage }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
